
lang: "en"

portal-tool:
  material: STICK
  name: "&5&lPGUtils &e&lTool"
  lore:
    - "&7Left Click on pos1"
    - "&7Right Click on pos1"

game-sb:
  title: "TestScore"
  teams: "%team_color%Team %team_id%: %team_point%"
  lines:
    - "====================="
    - "Time: %time%"
    - "%teams%"
    - "====================="

lobby-menu:
  title: "&bLobby"
  glow: false
  material: NETHER_STAR
  name: "&cLobby &e%id%"
  lore:
    - "&7Status: &c%status%"
    - "&7Online: &a&l%min%&7/&e&l%max%"


rewards:
  '1':
    type: command
    reward: give %player% diamond_block 1
    lobby: 1
  '2':
    type: item
    reward:
      material: CHISELED_STONE_BRICKS
      amount: 64
    lobby: 1