
lang: "en"

portal-tool:
  material: STICK
  name: "&5&lPGUtils &e&lTool"
  lore:
    - "&7Left Click on pos1"
    - "&7Right Click on pos1"

game-sb:
  title: "TestScore"
  timer: "Time: %time%"
  teams: "%team_color%Team %team_id%: %team_point%"


lobby-menu:
  title: "&bLobby"
  glow: false
  material: NETHER_STAR
  name: "&cLobby &e%id%"
  lore:
    - "&7Status: &c%status%"
    - "&7Online: &a&l%min%&7/&e&l%max%"

rewards:
  '1':
    type: command
    reward: 'say Hello %player%!'
    lobby: 1