
lang: "en"

database:
  type: "sqlite" ## mysql, sqlite
  host: 127.0.0.1
  port: 3306
  user: root
  pass: ""
  dbname: "pgutils"
  prefix: "pgutils_"



portal-tool:
  material: STICK
  name: "&5&lPGUtils &e&lTool"
  lore:
    - "&7Left Click on pos1"
    - "&7Right Click on pos1"

lobby-menu:
  title: "&bLobby"
  glow: false
  material: NETHER_STAR
  name: "&cLobby &e%id%"
  lore:
    - "&7Status: &c%status%"
    - "&7Online: &a&l%min%&7/&e&l%max%"

game-sb:
  title: "TestScore"
  teams: "Team %team_id%&7: &f%team_point%"
  lines:
    - "&c====================="
    - "Time: %time%"
    - "%teams%"
    - "&f====================="

whitelist-commands:
  - "pg"

rewards:
  '1':
    type: command
    reward: give %player% diamond_block 1
    lobby: 1
  '2':
    type: item
    reward:
      material: CHISELED_STONE_BRICKS
      amount: 64
    lobby: 1