database-type: SQLITE
debug-mode: false
idle-thread-pool-size: 3
database:
  sqlite:
    file-name: database.db
  mysql:
    host: jdbc:mysql://localhost:3306/your_database_name
    user: ''
    pass: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle-connection: 3
    maximum-pool-size: 10