name: PGUtils
version: 1.0
api-version: 1.20
author: [Penchev, ivan]
website: https://github.com/ivan100-ivoop/PGUtils
main: com.github.pgutils.Launcher

commands:
  pg:
    description: Reload the configuration.
    permission: pgutils.reload
    usage: "Usage: /pg <reload, setlobby, tool>"
      
permissions:
  pgutils.reload:
    permission-message: You do not have permission to use this command.
    default: op